spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mutuelle
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true

  liquibase:
    enabled: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: mutuelle-client
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8088/realms/mutuelle-realm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/mutuelle-realm
          jwk-set-uri: http://localhost:8088/realms/mutuelle-realm/protocol/openid-connect/certs

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    com.wbf.mutuelle: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

# Configuration Keycloak Admin Client
keycloak:
  auth-server-url: http://localhost:8088
  realm: mutuelle-realm
  admin-username: soumaila
  admin-password: admin

# =============================================
# CONFIGURATION KKIAPAY
# =============================================
kkiapay:
  base-url: https://api-sandbox.kkiapay.me
  api-key: 69a6eae91dfe93dd00cc51a7
  # À remplacer par vos vraies clés du dashboard Kkiapay
  secret-key: ${KKIAPAY_SECRET_KEY:developpement_secret_key}
  private-key: ${KKIAPAY_PRIVATE_KEY:developpement_private_key}
  public-key: ${KKIAPAY_PUBLIC_KEY:developpement_public_key}
  # URLs de callback (à ajuster selon votre déploiement)
  callback-url: http://localhost:8081/api/payments/callback
  success-url: http://localhost:3000/payment/success
  error-url: http://localhost:3000/payment/error

  # Configuration supplémentaire
  timeout: 30000  # timeout en millisecondes
  sandbox: true   # mode sandbox actif