spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mutuelle
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true



  liquibase:
    enabled: false

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: mutuelle-client
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:8088/realms/mutuelle-realm
            user-name-attribute: soumaila
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/mutuelle-realm
          jwk-set-uri: http://localhost:8088/realms/mutuelle-realm/protocol/openid-connect/certs

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    com.wbf.mutuelle: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

# Configuration Keycloak Admin Client
keycloak:
  auth-server-url: http://localhost:8088
  realm: mutuelle-realm
  admin-username: soumaila
  admin-password: admin

# =============================================
# CONFIGURATION KKIAPAY
# =============================================
kkiapay:
  base-url: https://kkiapay-redirect.com
  #api-key: 69a6eae91dfe93dd00cc51a7
  api-key: tpk_3011c9e2170a11f1b6a0874a5fa1f25d
  # À remplacer par vos vraies clés du dashboard Kkiapay
  secret-key: ${KKIAPAY_SECRET_KEY:sk_8ec7612a1b6755a98cdc7bf234d32fb3a3b6f70c8a5dc2f465dcf25532e71fa2}
  private-key: ${KKIAPAY_PRIVATE_KEY:pk_5195b216408e751d95d4a4c2e65d19249cb14fc2faee8094d4c4d2415fa9a295}
  public-key: ${KKIAPAY_PUBLIC_KEY:23c4757a0601fabd4c3d9e1bb5992c80a0db12cc}
  # URLs de callback (à ajuster selon votre déploiement)
  callback-url: http://localhost:8081/api/payments/callback
  success-url: http://localhost:3000/payment/success
  error-url: http://localhost:3000/payment/error

  # Configuration supplémentaire
  timeout: 30000  # timeout en millisecondes
  sandbox: true   # mode sandbox actif