spring:
liquibase:
    enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mutuelle}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8081}

# Configuration Keycloak
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8088}
  realm: ${KEYCLOAK_REALM:mutuelle-realm}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:soumaila}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

# Logging pour le debug
logging:
  level:
    com.wbf.mutuelle: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
